### ISSUE TITLE
License documentation

### ISSUE THREAD

**Issue by davidgiven** [jhallen/cpm#1]
Hello --- thanks for doing this; I used cpm-0.2.1 way back when for running Hitech C, but it only works on i386 architectures and as a result I'm out of luck on my ARM laptop...

However, is there any chance of having some more formal license documentation? As far as I can tell, Parag Patel's original code has an MIT-like license; the parts taken from cpm-0.2.1-mod2 are GPL; but your custom sections don't have a license at all. I assume the intention is either MIT or GPL --- it'd be good to have this written down!

(ZCPR2 and P2DOS seem to be more problematic as they largely predate licenses --- I've seen P2DOS described as 'public domain for non-commercial use', which makes no sense...)

**Comment by jhallen** [comment]
Sorry to take so long- I'll add the MIT license for my contribution.
