### ISSUE TITLE
No terminal output on big endian systems

### ISSUE THREAD

**Issue by racingmars** [jhallen/cpm#15]
On big endian systems (e.g. Linux on s390x), there is no terminal output even if `-DENDIAN_LITTLE` is removed from the CFLAGS in the Makefile. When BDOS tracing and -DDEBUGLOG is enabled, it appears the emulator is working correctly, there's just never any output written to the terminal.

Upon investigation, the problem is in vt.c in the putch() function:

```
void putch(int c) {	/* output character without postprocessing */
    write(fileno(stdout), &c, 1);
}
```

Because c is an int, it is presumably four bytes. On a little-endian system, the call to write() with a length of 1 works because the low-order byte of c is in the first byte in memory. On big-endian systems, though, the char value passed into c will end up in the fourth byte in memory so putch() is effectively always writing 0 to stdout.

Changing the signature of the function to ensure int values passed in are cast to chars fixes the problem:

```
void putch(unsigned char c) {	/* output character without postprocessing */
    write(fileno(stdout), &c, 1);
}
```

**Comment by jhallen** [comment]
Thanks, this is now fixed.
