### ISSUE TITLE
Doesn't run BASIC/Z

### ISSUE THREAD

**Issue by polluks2** [jhallen/cpm#16]
See https://www.facebook.com/groups/cpmusers/?multi_permalinks=2465660873609546%2C2465289176980049

**Comment by jhallen** [comment]
This is now fixed, except that it prints warnings about calling BDOS function 45.  I think BASIC/Z was intended for CP/M 2.2 on Heath H8, but this version of CP/M does not have BDOS fuctions 45... so I'm confused..

**Comment by polluks2** [comment]
Thank you, take a look https://www.seasip.info/Cpm/bdos.html#45
