### ISSUE TITLE
ZCPR1 and submit files

### ISSUE THREAD

**Issue by SteveFosdick** [jhallen/cpm#5]
I was doing some performance tests with this emulator, yaze-ag and z80 and, in the process found that submit files do not work correctly.  I could see that submit.com was creating a temporary file $$$.SUB but the command processor was failing to read it.

As the file cpm.c says this emulator uses ZCPR1 as its command process I looked up the source for that to see what was going on.

I found there were two main issues:

1. The ZCPR1 source says that the BDOS returns FF in A wen logging in a new disc that has any files with '$' in the filename in the directory.  I don't know if they found that by experimentation but that is certainly not mentioned in the DRI documentation I had access to.  ZCPR1 relies on that and skips looking for $$$.SUB if doing a disk reset returns 0.

2. The temporary file is backwards in that the last command is first and vice versa.  Whenever ZCPR regains control and finds a $$$.SUB file it reads the last record and then sets the record count (RC) to one less than it was previously before closing the file.  Real BDOS presumably writes the FCB back to the on-disk directory entry at this point thus this has the effect of truncating the file, i.e. chopping off the last record.  Eventually the file becomes zero-length after which ZCPR deletes it and goes back to prompting at the terminal.  The emulated BDOS was not truncating the host file and the fixrc function made sure the record count got set back to match the host file therefore ZCPR was reading the same command over and over.  What eventually stopped it was running out of available open files.

So that meant I had discovered another potential issue in that CP/M permits processes that only read from a file not to bother to close it.  ZCPR does this with .COM files it executes.  When ZCPR repeatedly executed the same command over and over again, each call to open the file would create a new entry in the stfps array and open another stdio stream.

In the attached patch I have solved these by:

1. Implementing the seach for '$' in the filenames in the current directory at disk reset.
2. Having the BDOS open file function check for the file being open already in the stfps array.  If it is then it does not open it again.
3. Having the close function truncate the file according to the RC value in the FCB but only if the S2/EX values are pointing to the last extent of the file.

I then discovered another bug in that the fixrc function sets rc based on the size of the file in the host directory structure but immediately following an fwrite it is possble some of the data recently written is in a memory buffer and has not yet made it into the file proper and thus is not reflected in that length.  I resolved this by adding an fflush immediately before the call to fixrc.
[bdos-patch.txt](https://github.com/jhallen/cpm/files/2129191/bdos-patch.txt)

**Comment by jhallen** [comment]
Thanks, I've taken your patch.  I never tried cpm submit...
